version: "2.1"

services:
  voicegame_v1:
    # image: alexstep/voicegame_v1
    build: ./
    labels:
      - "dapp in dao casino protocol"
    ports:
      - 8888:7777
    environment:
      - serverPort=7777
      - playerPrivateKey=0x9957197e15d3973c04a0c2287e43b9519b0e33cdebf443dd63bed78635957f61
      - bankrollerPrivateKey=0x5ed6b2001b4fa1da8c4ef71f2bf374c30223862c1efc5285d954acd62c17106a
      - PLATFORM_ID=mysuperplatformid
    entrypoint:
      ["sh", "./entrypoint.sh"]
